/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.landmanatee.ui;

import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class CheckUITest {
    @Test void checkDreamRouter() throws IOException {
        CheckUI ubiquiti = new CheckUI(null, null);
        assertFalse(ubiquiti.isInStock("https://store.ui.com/collections/unifi-network-unifi-os-consoles/products/dream-router"));
    }
}
